# Generated by Django 3.1.3 on 2020-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='title',
        ),
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
